site_name: Markmeld
site_logo: img/markmeld_logo_long.svg
site_url: http://markmeld.databio.org/
repo_url: http://github.com/databio/markmeld
pypi_name: markmeld

nav:
  - Getting Started:
      - Introduction: README.md
      - Install: install.md
      - Simple example tutorial: simple_example.md
      - Markmeld configuration: config_specification.md
  - How-to guides:
      - Customizing commands: commands.md
      - Writing jinja templates: jinja_template.md
      - Importing external files: imports.md
      - Inheriting from targets: inheriting.md
      - Prebuild and postbuild targets: side_targets.md
      - Multi-output targets: multi_output_targets.md
      - Target factories: target_factories.md
      - Advanced variable templates: variable_variables.md
      - Recursive rendering: recursive_rendering.md
      - Remote templates: remote_templates.md
      - Mail merges: mail_merge.md
  - Reference:
      - Changelog: changelog.md

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      jupyter_source: "docs_jupyter"
      jupyter_build: "docs_jupyter/build"
      # autodoc_package: "markmeld"
      no_top_level: true
  - search
